name: Automatically backup the lists
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN"
jobs:
  RunScript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Load secrets to environment variables
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Run PowerShell script
        shell: pwsh
        run: ./script.ps1
      - name: Commit changes
        shell: pwsh
        run: |
          git config --local user.email "41898282+github-actions[bot]@noreply.users.github.com"
          git config --local user.name "GitHub Actions[bot]"
          # Tell git to add all XML file to staging, ignore if file contains "Scrape failed" inside
          Get-ChildItem -Path "*" -Filter "*.*" -File  -Recurse | ForEach-Object {
            $inside = Get-Content $_.FullName
            if ($inside -contains "Scrape failed") {
              Write-Host "Skipping file: $_"
            } else {
              git add $_.FullName
            }
          }
          git commit -m "Backup lists, $(Get-Date -AsUtc -Format 'yyyy-MM-ddTHH:mm:ssZ')"
          git push
